import Cena from "./Cena.js";
import Sprite from "./Sprite.js";
console.log("Hello world!");
const canvas = document.querySelector("canvas");
console.log(canvas);
const cena1 = new Cena(canvas);
const ctx = canvas.getContext("2d");
cena1.desenhar();
const pc = new Sprite();
pc.desenhar(ctx);
const en1 = new Sprite({ x: 140, w: 30, color: "red" });
en1.desenhar(ctx);
